/* SPDX-License-Identifier: MIT */
package pro.digitalspace.android.passwords

import org.json.JSONArray
import org.json.JSONObject
import pro.digitalspace.android.security.DigitalSpaceCrypto
import pro.digitalspace.android.security.SecureStore
import pro.digitalspace.android.security.VaultSession
import java.security.MessageDigest
import java.security.SecureRandom
import java.time.Instant
import java.time.temporal.ChronoUnit
import javax.crypto.Cipher
import javax.crypto.Mac
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec

class PasswordVaultStore(private val secure: SecureStore, private val vault: VaultSession) {
    companion object {
        private const val INDEX="password-index-v1"; private const val AUDIT="password-audit-v1"; private const val TEAMS="password-teams-v1"
        private const val REVOCATIONS="password-revocations-v1"; private const val DOMAIN="Authentiverse/Vault/Passwords/v1"
        private const val RECORD_FORMAT="authentiverse-password-record-v1"; private const val BACKUP_FORMAT="authentiverse-password-backup-v1"
        private const val BACKUP_ITERATIONS=600_000; private val random=SecureRandom()
    }

    @Synchronized fun create(title:String, username:String, password:String, url:String="", notes:String="", totpBase32:String=""): PasswordCredentialSummary {
        require(title.trim().isNotBlank() && title.length<=160); require(password.isNotEmpty())
        val origins=mutableListOf<String>(); if(url.isNotBlank()) origins += CredentialOrigin.normalize(url)
        val now=Instant.now(); val record=PasswordCredentialRecord("cred_"+id(),title.trim(),username.trim(),password.encodeToByteArray(),url.trim(),origins,notes.take(16_384),TotpService.parseBase32(totpBase32),createdAt=now,updatedAt=now,passwordChangedAt=now)
        try { saveRecord(record); addIndex(record.credentialId); audit(record.credentialId,PasswordAuditAction.Created); return summary(record) } finally { record.destroy() }
    }

    @Synchronized fun update(id:String,title:String,username:String,password:String?,url:String,notes:String,totpBase32:String?): PasswordCredentialSummary {
        val record=loadRecord(id); try { ensureUsable(record);record.title=title.trim().take(160);record.username=username.trim().take(512);record.url=url.trim();record.allowedOrigins=mutableListOf<String>().apply{if(url.isNotBlank())add(CredentialOrigin.normalize(url))};record.notes=notes.take(16_384)
            if(password!=null){record.passwordUtf8.fill(0);record.passwordUtf8=password.encodeToByteArray();record.passwordChangedAt=Instant.now()};if(totpBase32!=null){record.totpSecret.fill(0);record.totpSecret=TotpService.parseBase32(totpBase32)};record.updatedAt=Instant.now();saveRecord(record);audit(id,PasswordAuditAction.Updated);return summary(record)}finally{record.destroy()}}
    @Synchronized fun delete(id:String){val record=loadRecord(id);try{if(record.scope==PasswordCredentialScope.Shared)ensureUsable(record);secure.delete(recordItem(id));val ids=index().filterNot{it==id};saveIndex(ids);audit(id,PasswordAuditAction.Deleted)}finally{record.destroy()}}
    @Synchronized fun list(query:String=""):List<PasswordCredentialSummary>{val q=query.trim().lowercase();return index().mapNotNull{id->runCatching{val r=loadRecord(id);try{if(r.access.usable()&&(q.isBlank()||listOf(r.title,r.username,r.url,r.notes,r.teamName.orEmpty()).any{it.lowercase().contains(q)}))summary(r) else null}finally{r.destroy()}}.getOrNull()}.sortedBy{it.title.lowercase()}}
    @Synchronized fun reveal(id:String):ByteArray{val r=loadRecord(id);try{ensureUsable(r);require(r.scope!=PasswordCredentialScope.Shared||r.access.canReveal){"This shared credential does not permit reveal."};audit(id,PasswordAuditAction.Revealed);return r.passwordUtf8.copyOf()}finally{r.destroy()}}
    @Synchronized fun totp(id:String):Pair<String,Int>{val r=loadRecord(id);try{ensureUsable(r);return TotpService.currentCode(r.totpSecret)}finally{r.destroy()}}
    @Synchronized fun findForOrigin(origin:String):List<PasswordCredentialSummary>{val normalized=CredentialOrigin.normalize(origin);return index().mapNotNull{id->val r=runCatching{loadRecord(id)}.getOrNull()?:return@mapNotNull null;try{if(r.access.usable()&&r.access.canAutofill&&CredentialOrigin.exactMatch(r,normalized))summary(r) else null}finally{r.destroy()}}}
    @Synchronized fun autofillSecret(id:String,origin:String):Pair<String,ByteArray>{val r=loadRecord(id);try{ensureUsable(r);require(r.access.canAutofill&&CredentialOrigin.exactMatch(r,origin)){"This credential is not approved for this exact origin."};audit(id,PasswordAuditAction.Autofilled,CredentialOrigin.normalize(origin));return r.username to r.passwordUtf8.copyOf()}finally{r.destroy()}}
    @Synchronized fun noteCopied(id:String){val r=loadRecord(id);try{ensureUsable(r);require(r.scope!=PasswordCredentialScope.Shared||r.access.canCopy){"This shared credential does not permit copy."};audit(id,PasswordAuditAction.Copied)}finally{r.destroy()}}
    @Synchronized fun health():PasswordHealthSummary{val records=index().mapNotNull{runCatching{loadRecord(it)}.getOrNull()};try{val hashes=records.groupBy{DigitalSpaceCrypto.hex(MessageDigest.getInstance("SHA-256").digest(it.passwordUtf8))};val reusedIds=hashes.values.filter{it.size>1}.flatten().map{it.credentialId};val now=Instant.now();return PasswordHealthSummary(records.size,records.count{isWeak(it.passwordUtf8)},reusedIds.size,records.count{it.passwordChangedAt.isBefore(now.minus(180,ChronoUnit.DAYS))},records.count{it.totpSecret.isEmpty()},reusedIds)}finally{records.forEach(PasswordCredentialRecord::destroy)}}

    @Synchronized fun teams():List<PasswordVaultTeam>{val bytes=vault.get(TEAMS)?:return emptyList();return try{val a=JSONArray(bytes.decodeToString());(0 until a.length()).map{PasswordVaultTeam.fromJson(a.getJSONObject(it))}}finally{bytes.fill(0)}}
    @Synchronized fun saveTeam(teamId:String?,name:String,members:List<String>):PasswordVaultTeam{require(name.trim().isNotBlank());val list=teams().toMutableList();val now=Instant.now();val team=if(teamId==null)PasswordVaultTeam("team_"+id(),name.trim(),members.distinct().toMutableList(),now,now)else list.first{it.teamId==teamId}.apply{this.name=name.trim();memberContactIds=members.distinct().toMutableList();updatedAt=now};list.removeAll{it.teamId==team.teamId};list+=team;val clear=JSONArray(list.map(PasswordVaultTeam::toJson)).toString().encodeToByteArray();try{vault.put(TEAMS,clear)}finally{clear.fill(0)};audit(null,if(teamId==null)PasswordAuditAction.TeamCreated else PasswordAuditAction.TeamUpdated,detail=team.name);return team}
    @Synchronized fun audits():List<PasswordAuditEvent>{val b=vault.get(AUDIT)?:return emptyList();return try{val a=JSONArray(b.decodeToString());(0 until a.length()).map{PasswordAuditEvent.fromJson(a.getJSONObject(it))}.sortedByDescending{it.at}}finally{b.fill(0)}}
    @Synchronized fun knownRevocation(shareId:String,issuer:String):Instant?{val b=vault.get(REVOCATIONS)?:return null;return try{JSONObject(b.decodeToString()).optString("$issuer|$shareId").takeIf(String::isNotBlank)?.let(Instant::parse)}finally{b.fill(0)}}
    @Synchronized fun recordRevocation(shareId:String,issuer:String,at:Instant){val b=vault.get(REVOCATIONS);val root=try{if(b==null)JSONObject() else JSONObject(b.decodeToString())}finally{b?.fill(0)};root.put("$issuer|$shareId",at.toString());val c=root.toString().encodeToByteArray();try{vault.put(REVOCATIONS,c)}finally{c.fill(0)}}

    @Synchronized fun exportBackup(passphrase:String):ByteArray{require(passphrase.length>=10){"Use a backup passphrase of at least 10 characters."};val records=JSONArray();index().forEach{id->val r=loadRecord(id);try{records.put(r.toJson())}finally{r.destroy()}};val payload=JSONObject().put("records",records).put("teams",JSONArray(teams().map(PasswordVaultTeam::toJson))).put("audit",JSONArray(audits().map(PasswordAuditEvent::toJson))).toString().encodeToByteArray();val salt=DigitalSpaceCrypto.random(16);val nonce=DigitalSpaceCrypto.random(12);val key=deriveBackupKey(passphrase,salt);return try{val sealed=DigitalSpaceCrypto.seal(payload,key,nonce,BACKUP_FORMAT.encodeToByteArray());audit(null,PasswordAuditAction.BackupExported);JSONObject().put("format",BACKUP_FORMAT).put("iterations",BACKUP_ITERATIONS).put("salt",DigitalSpaceCrypto.b64(salt)).put("nonce",DigitalSpaceCrypto.b64(nonce)).put("ciphertext",DigitalSpaceCrypto.b64(sealed.ciphertext)).put("tag",DigitalSpaceCrypto.b64(sealed.tag)).toString(2).encodeToByteArray()}finally{payload.fill(0);salt.fill(0);nonce.fill(0);key.fill(0)}}
    @Synchronized fun importBackup(bytes:ByteArray,passphrase:String,replace:Boolean=false):Int{val root=JSONObject(bytes.decodeToString());require(root.getString("format")==BACKUP_FORMAT);val salt=DigitalSpaceCrypto.unb64(root.getString("salt"));val nonce=DigitalSpaceCrypto.unb64(root.getString("nonce"));val cipher=DigitalSpaceCrypto.unb64(root.getString("ciphertext"));val tag=DigitalSpaceCrypto.unb64(root.getString("tag"));val key=deriveBackupKey(passphrase,salt,root.optInt("iterations",BACKUP_ITERATIONS));val clear=try{DigitalSpaceCrypto.open(cipher,tag,key,nonce,BACKUP_FORMAT.encodeToByteArray())}finally{salt.fill(0);nonce.fill(0);cipher.fill(0);tag.fill(0);key.fill(0)};return try{val payload=JSONObject(clear.decodeToString());if(replace){index().forEach{secure.delete(recordItem(it))};saveIndex(emptyList())};val a=payload.getJSONArray("records");var count=0;for(i in 0 until a.length()){val r=PasswordCredentialRecord.fromJson(a.getJSONObject(i));try{saveRecord(r);addIndex(r.credentialId);count++}finally{r.destroy()}};payload.optJSONArray("teams")?.let{arr->val teamBytes=arr.toString().encodeToByteArray();try{vault.put(TEAMS,teamBytes)}finally{teamBytes.fill(0)}};audit(null,PasswordAuditAction.BackupImported,detail="$count records");count}finally{clear.fill(0)}}

    @Synchronized fun indexExisting(id:String) { require(secure.exists(recordItem(id))); addIndex(id) }

    @Synchronized fun loadRecord(id:String):PasswordCredentialRecord{require(id.matches(Regex("cred_[0-9a-f]{32}")));val packed=secure.get(recordItem(id))?:throw NoSuchElementException("Credential not found.");val domain=vault.derivedKey(DOMAIN);return try{val root=JSONObject(packed.decodeToString());require(root.getString("format")==RECORD_FORMAT);val wrapNonce=DigitalSpaceCrypto.unb64(root.getString("wrap_nonce"));val wrapped=DigitalSpaceCrypto.unb64(root.getString("wrapped_dek"));val wrapTag=DigitalSpaceCrypto.unb64(root.getString("wrap_tag"));val dek=DigitalSpaceCrypto.open(wrapped,wrapTag,domain,wrapNonce,(RECORD_FORMAT+":"+id+":wrap").encodeToByteArray());try{val nonce=DigitalSpaceCrypto.unb64(root.getString("payload_nonce"));val cipher=DigitalSpaceCrypto.unb64(root.getString("payload"));val tag=DigitalSpaceCrypto.unb64(root.getString("payload_tag"));val clear=DigitalSpaceCrypto.open(cipher,tag,dek,nonce,(RECORD_FORMAT+":"+id+":payload").encodeToByteArray());try{PasswordCredentialRecord.fromJson(JSONObject(clear.decodeToString()))}finally{clear.fill(0);nonce.fill(0);cipher.fill(0);tag.fill(0)}}finally{dek.fill(0);wrapNonce.fill(0);wrapped.fill(0);wrapTag.fill(0)}}finally{packed.fill(0);domain.fill(0)}}
    @Synchronized fun saveRecord(record:PasswordCredentialRecord){require(record.credentialId.matches(Regex("cred_[0-9a-f]{32}")));val clear=record.toJson().toString().encodeToByteArray();val domain=vault.derivedKey(DOMAIN);val dek=DigitalSpaceCrypto.random(32);val wn=DigitalSpaceCrypto.random(12);val pn=DigitalSpaceCrypto.random(12);try{val w=DigitalSpaceCrypto.seal(dek,domain,wn,(RECORD_FORMAT+":"+record.credentialId+":wrap").encodeToByteArray());val p=DigitalSpaceCrypto.seal(clear,dek,pn,(RECORD_FORMAT+":"+record.credentialId+":payload").encodeToByteArray());val packed=JSONObject().put("format",RECORD_FORMAT).put("wrap_nonce",DigitalSpaceCrypto.b64(wn)).put("wrapped_dek",DigitalSpaceCrypto.b64(w.ciphertext)).put("wrap_tag",DigitalSpaceCrypto.b64(w.tag)).put("payload_nonce",DigitalSpaceCrypto.b64(pn)).put("payload",DigitalSpaceCrypto.b64(p.ciphertext)).put("payload_tag",DigitalSpaceCrypto.b64(p.tag)).toString().encodeToByteArray();try{secure.put(recordItem(record.credentialId),packed)}finally{packed.fill(0);w.ciphertext.fill(0);w.tag.fill(0);p.ciphertext.fill(0);p.tag.fill(0)}}finally{clear.fill(0);domain.fill(0);dek.fill(0);wn.fill(0);pn.fill(0)}}
    fun ensureUsable(record:PasswordCredentialRecord){require(record.access.usable()){ "This shared credential is expired or revoked." };record.access.shareId?.let{sid->record.access.issuerContactId?.let{issuer->knownRevocation(sid,issuer)?.let{throw IllegalStateException("This shared credential was revoked by its issuer.")}}}}

    private fun summary(r:PasswordCredentialRecord)=PasswordCredentialSummary(r.credentialId,r.title,r.username,r.url,r.allowedOrigins.toList(),r.notes,r.scope,r.teamId,r.teamName,r.access.copy(),r.issuedShares.toList(),r.passwordChangedAt,r.totpSecret.isNotEmpty(),isWeak(r.passwordUtf8))
    private fun isWeak(bytes:ByteArray):Boolean{val s=bytes.decodeToString();return s.length<12||s.all(Char::isLetter)||s.all(Char::isDigit)||s.lowercase() in setOf("password","password123","qwerty123","letmein","admin123")}
    private fun recordItem(id:String)="password-$id"
    private fun index():List<String>{val b=vault.get(INDEX)?:return emptyList();return try{val a=JSONArray(b.decodeToString());(0 until a.length()).map{a.getString(it)}.filter{it.matches(Regex("cred_[0-9a-f]{32}"))}.distinct()}finally{b.fill(0)}}
    private fun addIndex(id:String){if(id !in index())saveIndex(index()+id)}
    private fun saveIndex(ids:List<String>){val c=JSONArray(ids.distinct()).toString().encodeToByteArray();try{vault.put(INDEX,c)}finally{c.fill(0)}}
    private fun audit(credentialId:String?,action:PasswordAuditAction,origin:String?=null,detail:String?=null){val list=audits().toMutableList();list.add(PasswordAuditEvent("audit_"+id(),credentialId,action,origin,detail,Instant.now()));while(list.size>1000)list.removeAt(0);val c=JSONArray(list.map(PasswordAuditEvent::toJson)).toString().encodeToByteArray();try{vault.put(AUDIT,c)}finally{c.fill(0)}}
    private fun deriveBackupKey(passphrase:String,salt:ByteArray,iterations:Int=BACKUP_ITERATIONS):ByteArray{val chars=passphrase.toCharArray();return try{val spec=PBEKeySpec(chars,salt,iterations.coerceIn(100_000,2_000_000),256);try{SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).encoded}finally{spec.clearPassword()}}finally{chars.fill('\u0000')}}
    private fun id()=java.util.UUID.randomUUID().toString().replace("-","")
}
